version: '3'

services:
  app:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=example
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp:delegated

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: